### ISSUE TITLE
Rename package to `brainglobe-heatmap(s)`

### ISSUE THREAD

**Issue by LeonardoLupori** [brainglobe/brainglobe-heatmap#10]
Hey, thanks for the software, it's awesome!

I just wanted to let you know that on my side, after ` pip install bgheatmap` and a successful installation, I still could not import the package, getting the error:

`ModuleNotFoundError: No module named 'bgheatmap'`

looking in the site-packages folder of the conda env that I'm using I noticed that the package there is actually named `bgheatmaps` with the final s. In fact, `import bgheatmaps as bgh` works great.

Maybe I'm missing something absolutely trivial, but I found it to be a bit misleading

---
- win10
- clean conda environment with just brainrender and allensdk pip-installed

**Comment by FedeClaudi** [comment]
Hey thanks for highlighting this, likely a typo during package creation. I don't think it's worth creating a new release, hopefully it won't be too confusing. I'll leave this issue up so that people can see it if they also get confused

**Comment by vigji** [comment]
I think maybe it is worth, it sounds like it's likely to create some headaches!

**Comment by adamltyson** [comment]
We agreed in the [last dev meeting](https://github.com/brainglobe/BrainGlobe/discussions/350) to move to `brainglobe-xyz` as a standard, so I think this package should eventually be renamed `brainglobe-heatmap(s)`. I've changed the title to track better.
