### ISSUE TITLE
Update user guide 

### ISSUE THREAD

**Issue by leesuyee** [brainglobe/brainglobe-heatmap#64]
Some code changes have not been updated in the user guide and web guide, so the instructions do not run as it is w/o a few small text changes. The brain region values are initially set as a "regions" variable and is later called interchangeably as "regions" or "values." Additionally in the website guide here: https://brainglobe.info/documentation/brainglobe-heatmap/index.html#installation, bgh.heatmap should be converted to bgh.Heatmap.

**Comment by adamltyson** [comment]
Thanks @leesuyee, this should be fixed with https://github.com/brainglobe/brainglobe-heatmap/pull/66 and https://github.com/brainglobe/brainglobe.github.io/pull/263
